BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.3
        TextInput:
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        size_hint_y: 0.5
        text: 'Convert Kilometers to Miles'
    Label:
        size_hint_y: 0.5
        color: (1,1,0,1)
        text: 'Miles'
