BoxLayout:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: app.status_text
#    orientation: 'vertical'
#    GridLayout:
#        id: display_names
#    BoxLayout:
#        orientation: 'horizontal'
#        id: control_buttons
#        Button:
#            id: clear_button
#            text: 'Clear'
#    Label:
#        id: output_text
#        text: 'Output appears here'

